// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpog1L9fjAIEib9xTX0blF-VC0ivBzkVM',
    appId: '1:166792133376:web:8ded288dc328ab38b1d1e5',
    messagingSenderId: '166792133376',
    projectId: 'controleabastecimento-69576',
    authDomain: 'controleabastecimento-69576.firebaseapp.com',
    storageBucket: 'controleabastecimento-69576.firebasestorage.app',
    measurementId: 'G-YFXF16Q12E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBinJZ6v0VW-59A65stNnXwnwmTsFydZ1s',
    appId: '1:166792133376:android:cd8f812ef3477154b1d1e5',
    messagingSenderId: '166792133376',
    projectId: 'controleabastecimento-69576',
    storageBucket: 'controleabastecimento-69576.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXvbiT33ui9T4pv90G56CoBiEdV4eIjEs',
    appId: '1:166792133376:ios:e1d2fbdb4291d5ddb1d1e5',
    messagingSenderId: '166792133376',
    projectId: 'controleabastecimento-69576',
    storageBucket: 'controleabastecimento-69576.firebasestorage.app',
    iosBundleId: 'br.unigran.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXvbiT33ui9T4pv90G56CoBiEdV4eIjEs',
    appId: '1:166792133376:ios:e1d2fbdb4291d5ddb1d1e5',
    messagingSenderId: '166792133376',
    projectId: 'controleabastecimento-69576',
    storageBucket: 'controleabastecimento-69576.firebasestorage.app',
    iosBundleId: 'br.unigran.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpog1L9fjAIEib9xTX0blF-VC0ivBzkVM',
    appId: '1:166792133376:web:4c29e266f3f6baf2b1d1e5',
    messagingSenderId: '166792133376',
    projectId: 'controleabastecimento-69576',
    authDomain: 'controleabastecimento-69576.firebaseapp.com',
    storageBucket: 'controleabastecimento-69576.firebasestorage.app',
    measurementId: 'G-STQ6E14X24',
  );
}
